"""initial schema

Revision ID: 18c7f2b699b6
Revises: 
Create Date: 2026-09-08 21:14:41.731143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18c7f2b699b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_accounts',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.String(length=10), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email_accounts_email')
    )
    op.create_index(op.f('ix_email_accounts_email'), 'email_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_email_accounts_workspace_id'), 'email_accounts', ['workspace_id'], unique=False)
    op.create_table('leads',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('primary_type', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('international_phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_confidence', sa.String(length=10), nullable=True),
    sa.Column('email_source_url', sa.String(length=1000), nullable=True),
    sa.Column('google_maps_url', sa.String(length=2000), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('website_status', sa.String(length=20), nullable=False),
    sa.Column('website_score', sa.Float(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('lead_temperature', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.String(length=5), nullable=True),
    sa.Column('recommended_service', sa.String(length=255), nullable=True),
    sa.Column('recommended_action', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('why_this_lead', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('raw_google_data', sa.JSON(), nullable=True),
    sa.Column('raw_website_data', sa.JSON(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('website_strengths', sa.JSON(), nullable=True),
    sa.Column('website_weaknesses', sa.JSON(), nullable=True),
    sa.Column('detected_opportunities', sa.JSON(), nullable=True),
    sa.Column('contact_channels', sa.JSON(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'place_id', name='uq_leads_workspace_place')
    )
    op.create_index(op.f('ix_leads_business_name'), 'leads', ['business_name'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_lead_temperature'), 'leads', ['lead_temperature'], unique=False)
    op.create_index(op.f('ix_leads_opportunity_score'), 'leads', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_leads_place_id'), 'leads', ['place_id'], unique=False)
    op.create_index(op.f('ix_leads_priority'), 'leads', ['priority'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_table('search_presets',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_presets_workspace_id'), 'search_presets', ['workspace_id'], unique=False)
    op.create_table('searches',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('min_reviews', sa.Integer(), nullable=False),
    sa.Column('max_reviews', sa.Integer(), nullable=True),
    sa.Column('min_rating', sa.Float(), nullable=False),
    sa.Column('only_with_website', sa.Boolean(), nullable=False),
    sa.Column('only_with_phone', sa.Boolean(), nullable=False),
    sa.Column('try_find_email', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results_total', sa.Integer(), nullable=False),
    sa.Column('results_qualified', sa.Integer(), nullable=False),
    sa.Column('websites_analyzed', sa.Integer(), nullable=False),
    sa.Column('emails_found', sa.Integer(), nullable=False),
    sa.Column('hot_count', sa.Integer(), nullable=False),
    sa.Column('warm_count', sa.Integer(), nullable=False),
    sa.Column('cold_count', sa.Integer(), nullable=False),
    sa.Column('google_pages', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_query'), 'searches', ['query'], unique=False)
    op.create_index(op.f('ix_searches_status'), 'searches', ['status'], unique=False)
    op.create_index(op.f('ix_searches_workspace_id'), 'searches', ['workspace_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email', name='uq_suppression_workspace_email')
    )
    op.create_index(op.f('ix_suppression_list_email'), 'suppression_list', ['email'], unique=False)
    op.create_index(op.f('ix_suppression_list_workspace_id'), 'suppression_list', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('jobs',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=500), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_search_id'), 'jobs', ['search_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_table('proposals',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('opening', sa.Text(), nullable=True),
    sa.Column('personalized_observation', sa.Text(), nullable=True),
    sa.Column('strengths_json', sa.JSON(), nullable=True),
    sa.Column('opportunities_json', sa.JSON(), nullable=True),
    sa.Column('recommended_solution', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_reasoning', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_index(op.f('ix_proposals_workspace_id'), 'proposals', ['workspace_id'], unique=False)
    op.create_table('search_leads',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id', 'lead_id')
    )
    op.create_table('website_audits',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('audit_version', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('subscores', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('opportunities', sa.JSON(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_audits_lead_id'), 'website_audits', ['lead_id'], unique=False)
    op.create_index(op.f('ix_website_audits_workspace_id'), 'website_audits', ['workspace_id'], unique=False)
    op.create_table('emails',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('gmail_account_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gmail_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_account_id'), 'emails', ['gmail_account_id'], unique=False)
    op.create_index(op.f('ix_emails_lead_id'), 'emails', ['lead_id'], unique=False)
    op.create_index(op.f('ix_emails_proposal_id'), 'emails', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_workspace_id'), 'emails', ['workspace_id'], unique=False)
    op.create_table('website_pages',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['website_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_pages_audit_id'), 'website_pages', ['audit_id'], unique=False)
    op.create_table('email_events',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_email_id'), 'email_events', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_workspace_id'), 'email_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_events_workspace_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_email_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_website_pages_audit_id'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_emails_workspace_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_proposal_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_lead_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_account_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_website_audits_workspace_id'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_lead_id'), table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_table('search_leads')
    op.drop_index(op.f('ix_proposals_workspace_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_search_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_list_workspace_id'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_email'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_searches_workspace_id'), table_name='searches')
    op.drop_index(op.f('ix_searches_status'), table_name='searches')
    op.drop_index(op.f('ix_searches_query'), table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_search_presets_workspace_id'), table_name='search_presets')
    op.drop_table('search_presets')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_priority'), table_name='leads')
    op.drop_index(op.f('ix_leads_place_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_opportunity_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_temperature'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_name'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_email_accounts_workspace_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_email'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
